### ISSUE TITLE
Key

### ISSUE THREAD

**Issue by ArcticIsFrosty** [Pro-Swapper/ProSwapperLobby#4]
The key website gets stuck on generating key. I've turned off my ad blocker and tried restating the site and swapper, but the key never loads.

**Comment by KyeOnDiscord** [comment]
Can you show a video of opening the swapper and going through linkvertise to the key?

**Comment by SKULLONME21** [comment]
yeah the same thing is happening to me

**Comment by KyeOnDiscord** [comment]
Try using an incognito mode so any ad blocks or extensions don't interfere with the website. (Paste the key link into a new incognito window)
