### ISSUE TITLE
Some sort of crash or something. 

### ISSUE THREAD

**Issue by Collas42** [Pro-Swapper/ProSwapperLobby#5]
When I open the file ProSwapperLobby2.0.0.exe it worked the first time but my pc bluescreened I try again and now when I try it gives this error code "Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Program.Main(String[] args)" Not sure if this is on my end or something with the way it's coded sorry to bother if it's on me. :))

**Comment by KyeOnDiscord** [comment]
Press windows key +r and paste in `%localappdata%\Pro_Swapper\ProSwapperLobby`. Delete the configuration file in there and try reopening the swapper. Hope that helps

**Comment by anthony2-30** [comment]
i put the skin a own and then the skin a want but when i enter the game the skin i wanted is no there

**Comment by KyeOnDiscord** [comment]
> i put the skin a own and then the skin a want but when i enter the game the skin i wanted is no there

Make sure to not have high resolution textures installed -> https://docs.proswapper.xyz/pro-swapper/swaps-not-applying

Pro Swapper Lobby only shows in the Fortnite lobby and not in matches.
